performance = "High"
height = 438
width = 662
# env-vars = ['A', 'RIO=13']
padding-x = 10

# theme = "dracula"
theme = "rose-pine"

[editor]
program = "zed"
args = []

[keyboard]
use-kitty-keyboard-protocol = false
disable-ctlseqs-alt = false

[shell]
#program = "/opt/homebrew/bin/fish"
#args = ["--login"]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-c", "/Users/avelino"]

[navigation]
mode = "Plain"

[fonts]
family = "Maple Mono"
size = 22

[renderer]
performance = "High"
disable-unfocused-render = false

[developer]
enable-fps-counter = false
log-level = 'INFO'
