performance = "High"
height = 438
width = 662
# env-vars = ['A', 'RIO=13']
editor = 'code'

# theme = "dracula"
theme = "rose-pine"

[shell]
# shell = { program = "/opt/homebrew/bin/fish", args = ["--login"] }
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[navigation]
mode = "Plain"

[fonts]
family = "Maple Mono"
size = 22

[developer]
enable-fps-counter = false
log-level = 'INFO'
