performance = "High"
height = 438
width = 662
# env-vars = ['A', 'RIO=13']
editor = 'code'
padding-x = 10


# theme = "dracula"
theme = "rose-pine"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[navigation]
mode = "Plain"

[fonts]
family = "Maple Mono"
size = 22

[renderer]
performance = "High"
disable-unfocused-render = false

[developer]
enable-fps-counter = false
log-level = 'INFO'
