tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "puma/puma"
cask "java"
cask "xquartz"
brew "boost"
brew "caddy"
brew "carthage"
brew "clisp"
brew "rlwrap"
brew "clojure"
brew "cmake"
brew "cocoapods"
brew "coreutils"
brew "docker"
brew "emacs", args: ["with-ctags"], link: false
brew "ffmpeg"
brew "fzf"
brew "glew"
brew "gnupg", link: false
brew "go"
brew "htop"
brew "openssl"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "keychain"
brew "kompose"
brew "kubernetes-cli"
brew "leiningen"
brew "libarchive"
brew "libogg"
brew "libvorbis"
brew "lua@5.1"
brew "mas"
brew "mercurial"
brew "micro"
brew "mosh"
brew "nim"
brew "p7zip"
brew "phantomjs"
brew "physfs"
brew "poppler"
brew "pyenv-virtualenvwrapper"
brew "python"
brew "rbenv"
brew "rust"
brew "sbcl"
brew "scala"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "watch"
brew "wget"
brew "wxmac"
brew "zsh"
brew "puma/puma/puma-dev"
cask "alfred"
cask "android-ndk"
cask "appcleaner"
cask "caffeine"
cask "discord"
cask "docker"
cask "dropbox"
cask "emacs"
cask "expo-xde"
cask "filezilla"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-source-code-pro"
cask "google-chrome"
cask "gpg-suite"
cask "itau"
cask "iterm2"
cask "libreoffice"
cask "microsoft-office"
cask "ngrok"
cask "protonmail-bridge"
cask "quitter"
cask "sketch"
cask "skype"
cask "slack"
cask "spotify"
cask "telegram"
cask "tomighty"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
mas "1Password 7", id: 1333542190
mas "Airmail 3", id: 918858936
mas "Booster", id: 907023335
mas "DaisyDisk", id: 411643860
mas "iZip Unarchiver", id: 717545828
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "SIDT", id: 1308724728
mas "Twitter", id: 409789998
mas "WhatsApp", id: 1147396723
