tap "adoptopenjdk/openjdk"
tap "bukalapak/packages"
tap "buo/cask-upgrade"
tap "dart-lang/dart"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jeroenknoops/tap"
tap "johanhaleby/kubetail"
tap "mongodb/brew"
tap "puma/puma"
tap "railwaycat/emacsmacport"
tap "ravenac95/sudolikeaboss"
brew "antigen"
brew "openssl@1.1"
brew "aurora"
brew "readline"
brew "sqlite"
brew "awscli"
brew "boost"
brew "boost@1.59"
brew "caddy"
brew "python"
brew "carthage"
brew "gmp"
brew "cask"
brew "clisp"
brew "openjdk"
brew "rlwrap"
brew "clojure"
brew "cmake"
brew "cocoapods"
brew "composer"
brew "coreutils"
brew "ctop"
brew "direnv"
brew "docker", link: false
brew "drafter"
brew "wxmac"
brew "elixir"
brew "libogg"
brew "libvorbis"
brew "tesseract"
brew "ffmpeg"
brew "fzf"
brew "geckodriver"
brew "git"
brew "glew"
brew "gnupg", link: false
brew "go"
brew "htop"
brew "hub"
brew "hugo"
brew "libusbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick", link: false
brew "imagemagick@6", link: true
brew "ios-deploy"
brew "ironcli"
brew "keychain"
brew "kompose"
brew "kubernetes-cli"
brew "languagetool"
brew "leiningen"
brew "less"
brew "libarchive"
brew "libtensorflow"
brew "libyaml"
brew "lnav"
brew "lua@5.1"
brew "mas"
brew "maven"
brew "memcached"
brew "mercurial"
brew "micro"
brew "mosh"
brew "msmtp"
brew "multimarkdown"
brew "mysql"
brew "mysql-client"
brew "neomutt"
brew "neovim"
brew "nginx"
brew "nim"
brew "nnn"
brew "node"
brew "node@10"
brew "node@12"
brew "nvm"
brew "offlineimap"
brew "openal-soft"
brew "p7zip"
brew "pandoc"
brew "php"
brew "physfs"
brew "pipenv"
brew "poppler"
brew "postgresql", restart_service: true
brew "postgresql@9.6", restart_service: true
brew "pyenv-virtualenvwrapper"
brew "python@2", link: false
brew "rbenv"
brew "rclone"
brew "redis", restart_service: true
brew "rust"
brew "sbcl"
brew "scala"
brew "swiftlint"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "unrar"
brew "watch"
brew "weechat"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "zsh"
brew "bukalapak/packages/snowboard"
brew "dart-lang/dart/dart"
brew "github/gh/gh"
brew "heroku/brew/heroku"
brew "jeroenknoops/tap/gitin"
brew "johanhaleby/kubetail/kubetail"
brew "mongodb/brew/mongodb-community", link: false
brew "mongodb/brew/mongodb-community-shell"
brew "puma/puma/puma-dev"
brew "railwaycat/emacsmacport/emacs-mac", args: ["with-modern-icon"], link: false
brew "ravenac95/sudolikeaboss/sudolikeaboss"
cask "adoptopenjdk"
cask "alfred"
cask "android-ndk"
cask "android-platform-tools"
cask "android-sdk"
cask "android-studio"
cask "appcleaner"
cask "chromedriver"
cask "daisydisk"
cask "dbeaver-community"
cask "deepl"
cask "discord"
cask "docker-edge"
cask "expo-xde"
cask "figma"
cask "firefox-developer-edition"
cask "font-fira-code"
cask "font-hack-nerd-font"
cask "font-source-code-pro"
cask "garmin-express"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive-file-stream"
cask "gpg-suite"
cask "insomnia"
cask "intellij-idea"
cask "itau"
cask "iterm2"
cask "java"
cask "keepingyouawake"
cask "libreoffice"
cask "mactex"
cask "miro-formerly-realtimeboard"
cask "mongodb-compass-community"
cask "ngrok"
cask "phantomjs"
cask "pocket-casts"
cask "postico"
cask "protonmail-bridge"
cask "quitter"
cask "racket"
cask "sequel-pro"
cask "skype"
cask "slack"
cask "spotify"
cask "steam"
cask "telegram"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "xquartz"
cask "zoomus"
cask "zwift"
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "GarageBand", id: 682658836
mas "GravitDesigner", id: 1207744923
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Pocket", id: 568494494
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Trello", id: 1278508951
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
