[colors]
background       = '#232136'
black            = '#e0def4'
blue             = '#31748f'
cursor           = '#59546d'
cyan             = '#6e6a86'
foreground       = '#e0def4'
green            = '#56949f'
magenta          = '#ebbcba'
red              = '#ebbcba'
tabs             = '#797593'
tabs-active      = '#907aa9'
white            = '#e0def4'
yellow           = '#f6c177'
