[colors]
background       = '#faf4ed'
black            = '#575279'
blue             = '#286983'
cursor           = '#9893a5'
cyan             = '#9893a5'
foreground       = '#575279'
green            = '#56949f'
magenta          = '#d7827e'
red              = '#b4637a'
tabs             = '#797593'
tabs-active      = '#907aa9'
white            = '#fffaf3'
yellow           = '#ea9d34'
